services:
  redis:
    image: "redis:alpine"
    ports: ["6379:6379"]
  server:
    image: "ghcr.io/toktok/buildfarm-server"
    build:
      context: "."
      dockerfile: "server.Dockerfile"
    depends_on: ["redis"]
    ports: ["8980:8980"]
  worker:
    image: "ghcr.io/toktok/buildfarm-worker"
    build:
      context: "."
      dockerfile: "worker.Dockerfile"
    depends_on: ["server"]
    ports: ["8981:8981"]
    privileged: true
