---
_extends: .github

repository:
  name: dockerfiles
  description: Dockerfiles for (cross-)compiling TokTok projects for various platforms
  topics: docker, ghc, android, windows, qt, buildfarm, bazel

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - Codacy/PR Quality Review
          - CodeFactor
          - code-review/reviewable
