#!/bin/sh

# Install docker.
apk add make perl docker-cli

# Run this before set -eux so we don't print credentials to the CI logs.
echo "$DOCKER_PASS" | docker login --username "$DOCKER_USER" --password-stdin

set -eux

.github/scripts/build-image "$@"
