#!/bin/sh

# Install docker.
apk add make perl docker-cli

# Run this before set -eux so we don't print credentials to the CI logs.
echo "$DOCKER_PASS" | docker login --username "$DOCKER_USER" --password-stdin

set -eux

BUILD="$1"
IMAGE="$2"

make
docker pull "$IMAGE" || true
docker build --cache-from "$IMAGE" --tag "$IMAGE" "$BUILD"
docker push "$IMAGE"
