# vim:ft=dockerfile
FROM ubuntu:20.04
LABEL maintainer="@MAINTAINER@"

# Install required packages
COPY root-scripts/install-apt-dependencies.sh /root/
RUN ["/root/install-apt-dependencies.sh"]

# Activate deb-src lines in /etc/apt/sources.list.
COPY root-scripts/activate-src-debs.sh /root/
RUN ["/root/activate-src-debs.sh"]

# Create a new user 'androidbuilder'
COPY root-scripts/create-androidbuilder-user.sh /root/
RUN ["/root/create-androidbuilder-user.sh"]

# Log-in to the new user
USER androidbuilder
ENV HOME /home/androidbuilder

# Set the working directory
ENV BASE $HOME/ghc-build

# The adding of the patches happens later in the Docker build, just before the
# patched code is built
RUN mkdir -p $BASE/patches

COPY user-scripts/set-env.sh $BASE/

WORKDIR $BASE

#
# First we build GHC for the host architecture, since it can be shared between
# different Android architectures (Docker layer sharing).
#

COPY user-scripts/download-ghc.sh \
     user-scripts/build-ghc-host.sh \
     $BASE/
RUN ["./build-ghc-host.sh"]
