# https://raw.githubusercontent.com/dockcross/dockcross/master/Dockerfile
FROM dockcross/base
MAINTAINER @MAINTAINER@

# WINE is used as an emulator for try_run and tests with CMake.
# Other dependencies are from the listed MXE requirements:
#   http://mxe.cc/#requirements
# 'cmake' is omitted because it is installed from source in the base image
RUN apt-get update && apt-get -y --force-yes install \
  autoconf \
  automake \
  autopoint \
  bash \
  bison \
  bzip2 \
  flex \
  gettext \
  git \
  g++ \
  g++-multilib \
  gperf \
  intltool \
  libffi-dev \
  libgdk-pixbuf2.0-dev \
  libtool-bin \
  libltdl-dev \
  libssl-dev \
  libxml-parser-perl \
  libc6-dev-i386 \
  make \
  openssl \
  p7zip-full \
  patch \
  perl \
  pkg-config \
  python \
  ruby \
  scons \
  sed \
  unzip \
  wget \
  wine \
  xz-utils
# Install wine
RUN dpkg --add-architecture i386 && \
  apt-get update && \
  apt-get install -y wine32

WORKDIR /usr/src
# mxe master
RUN git clone https://github.com/mxe/mxe.git
WORKDIR /usr/src/mxe
COPY settings.mk /usr/src/mxe/
RUN make -j$(nproc)

ENV CROSS_TRIPLE=@TARGET_ARCH@-w64-mingw32.@LIBTYPE@

ENV WINEARCH=@WINEARCH@ \
    WINEDLLPATH=/usr/src/mxe/usr/${CROSS_TRIPLE}/bin \
    CMAKE_TOOLCHAIN_FILE=/usr/src/mxe/usr/${CROSS_TRIPLE}/share/cmake/mxe-conf.cmake \
    PATH=${PATH}:/usr/src/mxe/usr/bin \
    AS=/usr/src/mxe/usr/bin/${CROSS_TRIPLE}-as \
    AR=/usr/src/mxe/usr/bin/${CROSS_TRIPLE}-ar \
    CC=/usr/src/mxe/usr/bin/${CROSS_TRIPLE}-gcc \
    CPP=/usr/src/mxe/usr/bin/${CROSS_TRIPLE}-cpp \
    CXX=/usr/src/mxe/usr/bin/${CROSS_TRIPLE}-g++ \
    LD=/usr/src/mxe/usr/bin/${CROSS_TRIPLE}-ld \
    DEFAULT_DOCKCROSS_IMAGE=@FULLTAG@
RUN echo 'set(CMAKE_CROSSCOMPILING_EMULATOR "/usr/bin/wine")' >> ${CMAKE_TOOLCHAIN_FILE}

# Set up wine.
RUN wine hostname

WORKDIR /work

# Install packages needed to build toxcore.
RUN cd /usr/src/mxe \
&& make -j12 \
   check \
   libsodium \
   libvpx \
   opus \
&& make clean-junk clean-pkg
