# vim:ft=dockerfile
FROM toktoknet/ghc:8.10.3
LABEL maintainer="@MAINTAINER@"

#
# Start preparing the environment. This is where we branch off for different
# Android architectures.
#

COPY user-scripts/download-ndk.sh $BASE/
RUN ./download-ndk.sh

ENV \
 NDK_API=@NDK_API@ \
 NDK_ABI=@NDK_ABI@ \
 NDK_TARGET=@NDK_TARGET@ \
 NDK_TOOLCHAIN=@NDK_TOOLCHAIN@

COPY user-scripts/install-ndk.sh \
     user-scripts/unpack-ndk.pl \
     $BASE/
RUN ./install-ndk.sh

COPY user-scripts/set-env-android.sh $BASE/

#
# Build required libraries for Android.
#

COPY patches/iconv-* $BASE/patches/
COPY user-scripts/build-iconv.sh $BASE/
RUN ["./build-iconv.sh"]

COPY user-scripts/build-ncurses.sh $BASE/
RUN ["./build-ncurses.sh"]

COPY patches/gmp-* $BASE/patches/
COPY user-scripts/build-gmp.sh $BASE/
RUN ["./build-gmp.sh"]

COPY user-scripts/build-nettle.sh $BASE/
RUN ["./build-nettle.sh"]

COPY user-scripts/build-gnutls30.sh $BASE/
RUN ["./build-gnutls30.sh"]

COPY user-scripts/build-gpg-error.sh $BASE/
RUN ["./build-gpg-error.sh"]

COPY user-scripts/build-gcrypt.sh $BASE/
RUN ["./build-gcrypt.sh"]

COPY patches/gsasl-* $BASE/patches/
COPY user-scripts/build-gsasl.sh $BASE/
RUN ["./build-gsasl.sh"]

COPY user-scripts/build-libxml2.sh $BASE/
RUN ["./build-libxml2.sh"]

COPY user-scripts/build-libidn.sh $BASE/
RUN ["./build-libidn.sh"]

#
# At last we are ready to build the cross-compiler.
#

ENV ARCH_OPTS=@ARCH_OPTS@

COPY patches/ghc-* $BASE/patches/
COPY user-scripts/build-ghc-cross-compiler.sh $BASE/
RUN ["./build-ghc-cross-compiler.sh"]

COPY user-scripts/build-hsc2hs-wrapper.sh $BASE/
RUN ["./build-hsc2hs-wrapper.sh"]

COPY patches/cabal-wrapper $BASE/patches/
COPY user-scripts/build-cross-compile-cabal.sh $BASE/
RUN ["./build-cross-compile-cabal.sh"]

COPY user-scripts/install-happy.sh $BASE/
RUN ["./install-happy.sh"]

COPY user-scripts/add-bindir-links.sh $BASE/
RUN ["./add-bindir-links.sh"]

COPY user-scripts/update-cabal-install.sh $BASE/
RUN ["./update-cabal-install.sh"]

WORKDIR $HOME

#
# Now to add add some PATHs
#
ENV \
 GHC_HOST=$HOME/.ghc/android-host \
 PATH=$HOME/.cabal/bin:$HOME/.ghc/android-$NDK_API/$NDK_TOOLCHAIN/bin:$PATH \
 PLATFORM_PREFIX=$HOME/.ghc/android-$NDK_API/$NDK_TOOLCHAIN

COPY user-scripts/README $HOME/
RUN eval "echo \"$(cat $HOME/README)\""
