FROM @ORGNAME@/ghc-android:@VERSION@.@TARGET@
MAINTAINER @MAINTAINER@

WORKDIR $BASE

COPY user-scripts/build-libsodium.sh $BASE/
RUN ./build-libsodium.sh

#
# Install prerequisite haskell packages.
#
# distributive and comonad have a broken Setup.hs, so we need to configure with
# the host cabal and build with the target cabal. zlib needs a patch for FFI.
#
COPY patches/*.patch $BASE/patches/
COPY user-scripts/cabal-install-zlib.sh user-scripts/cabal-install-setup.sh $BASE/
RUN ./cabal-install-zlib.sh \
 && ./cabal-install-setup.sh distributive 0.5.0.2 \
 && ./cabal-install-setup.sh comonad 5

COPY install-deps.sh $BASE/
RUN ${NDK_TARGET}-cabal update \
 && ./install-deps.sh

WORKDIR $HOME

USER root
RUN apt-get install -y runit

ENTRYPOINT ["/home/androidbuilder/entrypoint.sh"]
WORKDIR /work
COPY user-scripts/entrypoint.sh /home/androidbuilder/
COPY user-scripts/target-cabal /home/androidbuilder/.cabal/bin/

COPY user-scripts/dockrun /root
